// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuiKkWxWb1MMZvuS4jbYmf8-XyqckDctg',
    appId: '1:1035629233394:web:a2193e9b9a0659af45bc6b',
    messagingSenderId: '1035629233394',
    projectId: 'otobus-2b767',
    authDomain: 'otobus-2b767.firebaseapp.com',
    databaseURL: 'https://otobus-2b767-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'otobus-2b767.appspot.com',
    measurementId: 'G-TKK3MQQ9RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Qojrd1tsAe7oePUdpnKFfY5PwhDtiSQ',
    appId: '1:1035629233394:android:73836674062d7ae945bc6b',
    messagingSenderId: '1035629233394',
    projectId: 'otobus-2b767',
    databaseURL: 'https://otobus-2b767-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'otobus-2b767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgy6nUIdGBnFaeXgQ_HW5sNvO75KpP_ew',
    appId: '1:1035629233394:ios:f5c65b80b988c3ae45bc6b',
    messagingSenderId: '1035629233394',
    projectId: 'otobus-2b767',
    databaseURL: 'https://otobus-2b767-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'otobus-2b767.appspot.com',
    iosClientId: '1035629233394-1ot8aurc1h643smdm7lkmfkqmrn09suc.apps.googleusercontent.com',
    iosBundleId: 'com.example.otobus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgy6nUIdGBnFaeXgQ_HW5sNvO75KpP_ew',
    appId: '1:1035629233394:ios:f5c65b80b988c3ae45bc6b',
    messagingSenderId: '1035629233394',
    projectId: 'otobus-2b767',
    databaseURL: 'https://otobus-2b767-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'otobus-2b767.appspot.com',
    iosClientId: '1035629233394-1ot8aurc1h643smdm7lkmfkqmrn09suc.apps.googleusercontent.com',
    iosBundleId: 'com.example.otobus',
  );
}
